### ISSUE TITLE
message ident not showing up in syslogd

### ISSUE THREAD

**Issue by bertramn** [graylog-labs/syslog4j-graylog2#12]
I was wondering what exactly needs to be configured to identify the application to syslogd? I tried below information:

``` java
syslog = Syslog.getInstance("unix_syslog");
config = syslog.getConfig();
config.setFacility(SyslogConstants.FACILITY_USER);
config.setThrowExceptionOnWrite(false);
config.setIdent("myapp");
config.setIncludeIdentInMessageModifier(true);
```

 But a `syslog.info("test me")` produces in `/var/log/messages`:

```
Jun  6 14:50:06 api02 -Xmx512m: test me
```

where I would expect:

```
Jun  6 14:50:06 api02 myapp: test me
```

Does anyone know how to configure this? Could not find anything in the [official documentation](http://www.syslog4j.org/docs/examples/examples.html).

**Comment by joschi** [comment]
This should be fixed by #20.
